### ISSUE TITLE
Regarding CNCF Automation issue

### ISSUE THREAD

**Issue by mayank-cse** [Alt-Shivam/Openstack#1]

**Comment by mayank-cse** [comment]
> 

Hi bro,
My name is mayank
I just got assigned for a task u worked on earlier can you help what do we have to do in that issue

**Comment by Alt-Shivam** [comment]
Yeah @mayank-cse 
Just research about the term 
adjust the information according to the Style Guide
Submit a PR
wait for the suggestions 
That's it

**Comment by mayank-cse** [comment]
Yeah I did the same what they suggest

**Comment by Alt-Shivam** [comment]
For anything else 
you can reach me out on Slack
or  [linkedin](https://www.linkedin.com/in/shivank-chaudhary-a67681202/)
